services:
  backend:
    build: ./backend
    container_name: dummy-backend
    ports:
      - "3000:3000"
    networks:
      - dummy-network
    command: sh -c "npm start"

  frontend:
    build: ./frontend
    container_name: dummy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - dummy-network

networks:
  dummy-network:
    driver: bridge